apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: api
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-influxdb
