apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-influxdb
  labels:
    {{- include "garmin-grafana.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-influxdb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-influxdb
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

{{- if .Values.influxdb.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-influxdb
{{- else }}
      volumes:
        - name: data
          emptyDir: {}
{{- end }}

      containers:
        - name: influxdb
          image: "{{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}"
          ports:
            - containerPort: 8086
              name: api
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-credentials
          env:
{{- range .Values.influxdb.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
